### ISSUE TITLE
Create code norms document

### ISSUE THREAD

**Issue by sblackstealth** [sblackstealth/Footprint-App#2]

**Comment by sblackstealth** [comment]
➤ Roderick Monje commented:

Rather than making a document people have to manually follow, how about incorporating a linter that automatically checks style, say, upon commit? Violations of style would then cause CI to fail.

**Comment by ivanoblomov** [comment]
Because the linter is effectively self-documenting, this is closed by https://github.com/sblackstealth/Footprint-App/pull/20.
