### ISSUE TITLE
Integrate Trello

### ISSUE THREAD

**Issue by ivanoblomov** [sblackstealth/Footprint-App#21]
Stakeholders: entire team

## Goal

Integrate Trello with GitHub.

## Description

We’re using Trello to manage the project. Let’s integrate it with GitHub issues for efficiency. 

## Success Criteria

Successful integration with Trello or a consensus not to and why.

**Comment by ivanoblomov** [comment]
@sblackstealth is this a good idea or not? Pros include it’ll save us duplicate effort (adding tasks in both Trello and here). Cons include not every Trello task can be addressed in GitHub.

**Comment by ivanoblomov** [comment]
Alternatively, we could use [GitHub's built-in PM tool](https://github.com/sblackstealth/Footprint-App/projects).

**Comment by sblackstealth** [comment]
@ivanoblomov I think its a great idea. I already have it synched to Trello. I think we can assign only Github task on Trello for now
