### ISSUE TITLE
Add a static analyzer

### ISSUE THREAD

**Issue by ivanoblomov** [sblackstealth/Footprint-App#25]
Stakeholders: engineering

## Goal

Add a static analyzer to improve code quality.

## Description

Integrating a static analyzer such as Code Climate can generate [code-quality reports](https://codeclimate.com/github/ivanoblomov/google_maps_geocoder) with every push.

## Success Criteria

If approved, the README will reflect master's current code quality with a ["maintainability" badge](https://github.com/ivanoblomov/google_maps_geocoder).

**Comment by sblackstealth** [comment]
Done

**Comment by ivanoblomov** [comment]
How is this done? Did I miss something?

**Comment by ivanoblomov** [comment]
Closed by https://github.com/sblackstealth/Footprint-App/commit/02ff38fdf9c846a7c9e72854371a7a29114476a1.
