### ISSUE TITLE
Disconnect CircleCI from GitHub

### ISSUE THREAD

**Issue by ivanoblomov** [sblackstealth/Footprint-App#34]
Stakeholders: engineering

## Description

CircleCI is still reporting failures even though we removed it from the repo.

## Steps to Reproduce

1. Push a change to the repo.
2. CircleCI [runs a build](https://circleci.com/gh/sblackstealth).

**Comment by ivanoblomov** [comment]
@sblackstealth giving this to you since I don't have access.

**Comment by sblackstealth** [comment]
disconnected Circleci from app on . Circleci dashboard
